### ISSUE TITLE
Certain cursors (like hyperlink hand) are way too big (like 16x big)

### ISSUE THREAD

**Issue by mjbaldwin** [alexzielenski/Mousecape#100]
I love Mousecape, I'm using 0.0.6 with macOS 10.14.3 (Mojave). I use it to make the pointer a left-handed version. In the past, when I apply the cape, sometimes certain cursors (hyperlink hand, resize arrows) would be incredibly large for a few minutes (like 4x the size on each side for 16x area), but would eventually switch to correct size.

But I restarted my computer today, and ran Mousecape to swtich to left-handed versions, and the large cursors won't go away. The arrow pointer is correct size, but hyperlink-hand and window resize arrows are the same 16x area.

Note that I've always used the Preferences to set cursor scale to 1.53. That scale is correctly applied for the normal pointing arrow.

Unfortunately I don't know how to take a screenshot because the screenshot tool doesn't include the cursor of course...

**Comment by alexzielenski** [comment]
This is a known issue with mousecape where if you apply a new cape that did not modify the same cursors as the last applied some will stick around. I believe this will be solved by logout/reboot.

Im aware this issue is quite old, sorry for my inactivity. Let me know if the issue persists.

Hope you are still enjoying mousecape!
