### ISSUE TITLE
Where are my cursors?

### ISSUE THREAD

**Issue by CanceIIed** [alexzielenski/Mousecape#117]
I lost my cursor settings and entire Mousecape functionality today. The app does not even open anymore.

**Comment by DaniBedz** [comment]
I don't understand why, but I think a silent OSX update broke things.
The issue is open here: [https://github.com/alexzielenski/Mousecape/issues/116](https://github.com/alexzielenski/Mousecape/issues/116)

In the meantime, you can use this older version:
[https://github.com/alexzielenski/Mousecape/releases/tag/0.0.6b2](https://github.com/alexzielenski/Mousecape/releases/tag/0.0.6b2)

You should just be able to replace the old file in your Applications folder and your old settings will be preserved. Lovely stuff.

**Comment by alexzielenski** [comment]
This was an issue with my erroneous uploading a build that was ad-hoc codesigned. Build 1813 should pass this check properly.

https://github.com/alexzielenski/Mousecape/releases/tag/1813
