### ISSUE TITLE
How to change cursor for Terminal app

### ISSUE THREAD

**Issue by webOS101** [alexzielenski/Mousecape#121]
I've downloaded a cape (Obsidian) and activated it (as well as activated the helper tool).  The I-Beam cursor shows up correctly in all the apps I've tested so far, except Terminal.  How can I get the cursor to show up correctly in Terminal?  I'm running High Sierra.

**Comment by NordJan** [comment]
I have checked here and with my cursor, the formidable Solara (by Skinplant), it also doesn't show the iBeam cursor of the .cape, but just the regular one. So, I guess Terminal is an exception. Try to live with this and enjoy Mousecape for the rest. Cheers.

**Comment by lmaoguy123** [comment]
You cant....

**Comment by MUI68K** [comment]
I _**think**_ that the reason that Mousecape doesn't theme the cursor for Terminal is that there's new or existing IBeam cursors inside the Terminal.app - Also a possible new cursor called IBeamMR

I don't know, yet, how to code or understand code that can re-assign this. I think the solution is to create a script to first backup -> copy in new resources directly to the Terminal.app Resources folder.  

It wasn't the case earlier on that Mousecape couldn't theme the IBeam cursor in Terminal. I got flack for the IBeam cursors because they weren't great for selecting. That's my memory anyway.

**Comment by webOS101** [comment]
I believe I found the answer!  Use the following command:

```
defaults write com.apple.Terminal UseCustomIBeamCursor -bool NO
```

Then the IBeam from Mousecape will show!
