### ISSUE TITLE
Feature request: support cur/ani files?

### ISSUE THREAD

**Issue by mmoayyed** [alexzielenski/Mousecape#48]
Is it possible for Mousecape to support windows cursor file formats such as cur/ani? My understanding is that each file contains one cursor only, and so supporting those formats would hopefully increase the adoption of the product and does not require folks to create custom capes.

**Comment by derekustruck** [comment]
What file format should the animated cursor be saved as? I've tried TIFF with layers, but I am not getting a successful animation.

**Comment by alexzielenski** [comment]
They should be in one image with each frame stacked vertically in order

**Comment by derekustruck** [comment]
Not to argue with you, because you have a fine product, but I read that in the readme and it is hardly what I would call clear technical writing.

Especially considering that most image manipulation softwares have a semantic overlap with your description, in that layers stack vertically as well. Furthermore, Tiffs can be saved with that layer information, further confusing the issue.

As I said, the comment in the code was far clearer than the information in the readme.

Thanks!
