### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by HarryAwesome06** [alexzielenski/Mousecape#74]
Anytime I create a new arrow for my pack, I drag the file into the 1x, 2x, 5x, 10x. But my .ani doesn't show up. I don't really know how to use them, but I just need someone to tell me... How in the world do I view a .ani file and its frames to add it?! And how do you stack frame on top on a frame like it says to do to make it work? I'm very confused.

**Comment by ExactProbability** [comment]
Hi,

After having done some cursors on previous occasions, here's what I did or do. 

In order to view the .ani file there's a program for Windows that is called AniTuner2 from http://www.gdgsoft.com/download/anituner.aspx

You would need to install WineBottler for Mac in order to install this program. It works fine as I've been previewing plenty of converted Mac cursors to the Windows counterpart. If you have experience with Wine (WineBottler or that other Mac program I forget the name of right now) then try to install that program I linked to. 

That would at least allow you to view .ani files.

In order to create the animation for macOS using Mousecape you would have to do a little work. I think that AniTuner2 lets you export individual frames but I doubt that the exported images will be of any use for Mousecape.

There's another program also for Windows(sorry - but these programs are free and can be dealt with easily using WineBottler for instance) The program is called Greenfish Icon Editor. Having not made any cursors lately I would personally like to get back in the game of making some. One link to the program mentioned is here: https://gfie.codeplex.com

If you have made some different .PNG frames that you'd like to import into Mousecape then you take one frame(.png) at a time and hold down the Option-key on the keyboard while dragging the image on to the respective wells that you'd like to see animated. That of course requires that you have the individual images to begin with from a .ani cursor. There's also the Commandline tool called cursorflip on the Download page of Mousecape that I have had nothing but bad luck using due to the amount of frames often used in Windows exceeds those that Mousecape can handle.

**Comment by HarryAwesome06** [comment]
Nice, but I'm on a OS X... 🆘

**Comment by ExactProbability** [comment]
Only commenting like I did due to the fact that I too use macOS or OS X and that's what I found helped me through.

**Comment by ExactProbability** [comment]
I might have answered you totally off mark. I assumed something about the .ani Windows file format.

I'm sorry for confusing the hell out of you. I can understand your reply much better.

Currently there's no way of viewing your animation for Mousecape but to see the animation unfold in the placeholders of those 1x 2x 5x and 10x. You can save a lot of work by making just the 1x and 2x.

If you want to create a whole long animation for Mousecape without dragging and dropping each instance in then create a, for regular size: 32px wide by 96px tall (that's 4 frames to see)
You can use Photoshop to do this or what ever other app you use to draw. The advantage of this is the possibilty of going back to the drawing app to adjust if the content on the second frame is slightly off.

In your drawing app on the Mac you will have to drag some rulers in to see and make certain that your anmation lines up in the 32px by 32px frame. And then on to the next 32px by 32px frame until you have your 4 frames done. Now export your image as a transparent PNG. Drag that into the Mousecape placeholder for 1x and adjust the frames for it in Mousecape if the app does not adjust, then add some Frame Duration and adjust the Hotspot. Hotspot position is not to be totally on point on the animation but try and place it nicely anyway. 

My UNITY2016 cursor set(non-revised) featured a few colors and the red animation one is seen in the video link at my Droplr account. I've attached the transparent animation here on GitHub.
![unity2016-animation-workinginthebackground-red](https://cloud.githubusercontent.com/assets/25787371/23026138/9a81d68e-f460-11e6-91c1-707594a3c073.png)

Link to video showcase; http://d.pr/v/zIfx+
