### ISSUE TITLE
Animated cursor (Arrow) prevents HyperDock to show window previews

### ISSUE THREAD

**Issue by stendagslott** [alexzielenski/Mousecape#77]
The title explains it well. When I have an animated cursor for the "Arrow" pointer, it prevents HyperDock to show window previews. If I use a non-animated cursor, HyperDock shows the window previews. I have included my Helix pointer that I have converted from Renzo Riccios great work in case you don't have an animated Arrow pointer. I have also noticed that the pointer flickers when typing if the pointer is outside of the typing area (i.e. not showing as an IBeam)
[local.sten.Helix.cape.zip](https://github.com/alexzielenski/Mousecape/files/1150294/local.sten.Helix.cape.zip)

**Comment by alexzielenski** [comment]
I notice this flickering sometimes typing with this set as well. It seems to me that apple's code for setting the cursor while typing is getting triggered excessively. As far as Hyperdock goes, I haven't the slightest clue how mousecape animated cursors could affect something like that.

Closing this issue since it is old, if this problem still occurs for you please reopen.
