### ISSUE TITLE
All of my cursor sets are pale on High Sierra. Very sad.

### ISSUE THREAD

**Issue by ghost** [alexzielenski/Mousecape#89]
Hi Alex,

I hope that you are willing to take a look at why all(except a few it would appear) of imported or newly created cursors are all pale with the most recent Mousecape release and High Sierra. I know I'm not the only one using Mousecape who are are experiencing this issue. Some have reached out to me asking why my cursors are pale(loss of colors)

I can't help them but I hope you can

Here's an example: Some like Grove, Pointing, Glemsom and Mode2 are all new but are pale.
<img width="502" alt="lossofcolors" src="https://user-images.githubusercontent.com/25787371/39200368-4836dc4a-47ec-11e8-8003-63c3f6a23c03.png">

**Comment by GhostValk** [comment]
I upgraded to High Sierra a week ago and everything is working normal in mousecape.

**Comment by ExactProbability** [comment]
I don't know what seems to be the issue on my Mac then. I have just reinstalled High Sierra again today with the same issues only not the same exact cursors are affected.

**Comment by NordJan** [comment]
Could you upload one of the pale cursor sets? So I can check how they look on my Mac.
Kind regards,
Nord-Jan Vermeer

**Comment by ExactProbability** [comment]
Here's one
[com.allan.unity2016Blue.cape.zip](https://github.com/alexzielenski/Mousecape/files/1956582/com.allan.unity2016Blue.cape.zip)

**Comment by ExactProbability** [comment]
Could it be the APFS filesystem?

**Comment by NordJan** [comment]
Here's how my Mousecape app looks, with "unity2016Blue" at the bottom, pale  :-(
All the others look as they always have.
<img width="967" alt="2018-04-27 10 36 51 pm" src="https://user-images.githubusercontent.com/8850154/39384086-ed7a3798-4a6b-11e8-90b8-c82e8abcb16e.png">

Please try how "Solara" looks at your Mac.
[Solara.SkinPlant.cape.zip](https://github.com/alexzielenski/Mousecape/files/1956598/Solara.SkinPlant.cape.zip)

**Comment by ExactProbability** [comment]
It's the same type of overlay;
<img width="398" alt="screen shot 2018-04-27 at 22 42 19" src="https://user-images.githubusercontent.com/25787371/39384232-5a3fd0cc-4a6c-11e8-9d60-7a27561c8488.png">


Some of my recent cursors are okay until I edit them and apply them - after that they turn pale.

**Comment by NordJan** [comment]
What happens with Unity2018Blue if you do a "Dump Cursors..."? It's under Capes. All cursors are places in the same order, and the missing ones are filled with default ones. Are the default ones pale too, in the dumped set?

**Comment by ExactProbability** [comment]
Yes they are.

**Comment by ExactProbability** [comment]
Are you using a HFS formatted drive? I'm using a Apfs one - I was wondering if that's the real issue

**Comment by NordJan** [comment]
No, since High Sierra I have APFS too.
Here's a weird thing: when I choose yoyr set and do multiple "Dump Cursor...", it seems as if your set is getting paler and paler, first from the bottom is the first dump and then 2 times more:
<img width="1013" alt="2018-04-27 10 58 03 pm" src="https://user-images.githubusercontent.com/8850154/39384963-d04c339e-4a6e-11e8-950a-f86bacedc1fa.png">

**Comment by ExactProbability** [comment]
A weird thing is that if I re-create or make some cursors using Affinity Designer - like the Haand one and an orange one I'm making - then export as PSD files for import as a cursor. The paleness doesn't occur, despite edits and re-applies

I thought the Sonara looked rather nice so I wanted to try an orange cursor.

**Comment by NordJan** [comment]
One more guess: Solara only has the 1x, your has 1x, 2x, 5x and 10x included. What about stripping to only leave the 1x and see hat happens. It might be something like interpolation of high-res, resulting in something "shabby".

**Comment by ExactProbability** [comment]
Exactly - It might be an issue. I've made some sets using only 2x because I'm on retina and so far they are okay. I've just added a 32x32px cursor to the current orange set I'm making and there's no issues with that as of yet. Let me try and reopen mousecape app. -- yes there it is. Mousecape upon launching again makes my new set pale.

**Comment by NordJan** [comment]
Last observation (before a week vacation): when Unity2016Blue is imported, while Mousecape is running, it shows some cursors non-pale (eg Resize E and Resize N). But after closing and re-opening, all cursors in the set are pale. So, it seems Mousecape is altering the file, in some way.
<img width="1004" alt="2018-04-27 11 25 24 pm" src="https://user-images.githubusercontent.com/8850154/39386388-bb4ee04e-4a74-11e8-84f9-9dda6623c591.png">
<img width="1003" alt="2018-04-27 11 25 55 pm" src="https://user-images.githubusercontent.com/8850154/39386396-bf024190-4a74-11e8-966a-5ec07ac27c4d.png">

The .cape files are just xml-files, so you might try to do a diff on changes. I noticed a difference, at least in file size, between the .cape you send me (351KB) and the .cape which is placed in the directory after importing (374KB). Might there be a translation to or from RGB or .png to binary? Just guessing now. Cheers and good luck.

**Comment by Anais-Et-Vous** [comment]
Did we get any luck with this? I've been using pale cursors for some time. Seems so far only my least desirable cursors seem to be working sadly. I've created sets in every which way etc but I can't work it out. I'm using a non retina old macbook pro 2011, running Mojave but on a patched version for unsupported macs... does this have something to do with it? I've just purchased an SSD to replace my HDD today so should I be formatting it in a particular way? I see you mentioned AFPS etc up there, does it help? Thanks...

**Comment by NordJan** [comment]
To be honest, I haven't looked into this any further. I have postponed upgrading to Mojave for another reasons, but this one is added by now.
Regarding file systems, I think this has no effect on MouseCape. I expect the paleness issue to be an internal matter, due to conversion and/or Retina related.

**Comment by ExactProbability** [comment]
I also haven't looked into it any further. I did however make an update to an existing cursor set around September 2018 https://www.deviantart.com/allannyholm/art/Ignite-mousecape-hotspot-fix-update-735053168 and I have managed to use that without it going pale by using the terminal to apply this cursor set by using the mousecloak command. I believe also on Mojave. I'm just not going to make any more cursors because of the current bugs and that I can't trust Mousecape doing its thing correctly on newer macOS. The last known working Mac OS for me was El Capitan. Everything after that went downhill. The issue I have with the Mousecape app is that once I apply a cursor set within the app itself there's no way around my cursors being pale. Only the terminal command helps. Once I build a cursor set inside Mousecape, by dragging and dropping files in, I stop using Mousecape as a whole and turn to the Terminal. If I do become so bold as to edit a hotspot and save the file within Mousecape a second time then there's no helping me. Not even with the Terminal command called mousecloak. The linked cursor set from my dA account was built up from scratch a couple of times because I forgot all about what not to do. That really was suckage big time. If I was(despite what ever I wrote) to make any new set I would have to remember to follow the rules I set up for myself and never ever touch the curset set made within Mousecape ever again. Not even to change version number or a hotspot. I'm using a Fusion Drive with APFS filesystem. Not even HFS+ during High Sierra would be of any use.

**Comment by alexzielenski** [comment]
@ExactProbability try the 0.0.6b1 build on the releases page

**Comment by alexzielenski** [comment]
Also, @ExactProbability I love this icon: https://www.deviantart.com/allannyholm/art/Mousecape-AppIcon-723046917

May I include in next release?

**Comment by ExactProbability** [comment]
@alexzielenski The updated Mousecape build works 100% for me now with all my cursors intact.

You can most certainly use and include the icon linked in the next release of Mousecape 😄 

I'm now one step closer to previous glory days of theming - ThemeEngine is missing in that equation 😢 

Thank you so much for investigating the issue and fixing Mousecape. Happy New Year! 🎆

**Comment by gavinbrockis** [comment]
Thanks, I was having the same issue and the beta update sorted it :)
