### ISSUE TITLE
Mousecape doesn't apply on startup

### ISSUE THREAD

**Issue by xtien** [alexzielenski/Mousecape#96]
I have to run mousecape after I start my mac. How do I make it run at startup automatically?

**Comment by sanssecours** [comment]
One option is to add the application `com.alexzielenski.mousecloakhelper` in the directory `Mousecape.app/Contents/Library/LoginItems` to “Login Items” in “System Preferences” → “Users & Groups”. For more information please take a look at issue #64.

**Comment by hipunk** [comment]
All those tips don't work for me.
Helpertool installed, helpertool not installed, cloakhelper in login items, cloakhelper not in login items. Doesn't matter, it doesn't launch.
Version 0.0.6 and 0.0.6b, Mac OS X 10.13.6.

Why wait for the fix when there's AppleScript - copy and paste everything below into Script Editor.app (formerly AppleScript Editor.app), save it as an Application and put that newly created AppleScript Application into your startup items. Read the comments in the script.

```
-- written by hipunk
-- Public Domain

-- launch Mousecape
tell application "Mousecape" to activate

tell application "System Events"
	
	-- I wish to set my cursor to the 11th cursor in my Mousecape list
	-- If the cursor you wish to use is the e.g. the second cursor
	-- in your Mousecape list, change the 11 to a 2. If there's only
	-- one cape (at the top) in your Mousecape list, change it to a 0.
	-- key code 125 is the arrow down key
	repeat 11 times
		key code 125
	end repeat
	
	-- key code 36 is the enter key, as command + enter sets the cape
	key code 36 using command down
	
end tell

-- Job done
tell application "Mousecape" to quit
```

I love Mousecape, it's the best thing since sliced cheese!

**Comment by fnankivell** [comment]
Same problem here. Version 0.5 would work just fine at launch using the trick *sanssecours* mentionned in the 2nd post. Tried the smart AppleScript by *hipunkk* but no luck either.

I'm on Mojave 10.14.3, will revert to 0.5 until Alex can figure out a fix, even if I get the pale cursor problem that's not really a bother for me.

Thanks Alex for keeping Mousecape alive!

**Comment by hipunk** [comment]
>Tried the smart AppleScript by _hipunkk_ but no luck either.

Works for me. 

However I fixed it:

Open Automator.app (`/Applications/Automator.app`), press `Command-N` if you're not being asked about a `new document` already. For the type of your document select `"Application"`.
From the left, drag and drop the `"Run AppleScript"` list item to the right side of the window.
Click `"Options"` and set checkbox `"Ignore this action's input"` to `enabled`.
Replace everything in the AppleScript editor field within Automator on the right with the following:

```

-- Copyright (C) 2019 hipunk

on run {input, parameters}
	
	-- login launch Mousecape
	
	
	global cursorSelection
	
	-- ***********************************************************************
	-- cursorSelection represents the n-th cursor in your Mousecape list
	-- E.g. if you wish to set your cursor to the first cursor in your Mousecape list
	-- aka. the one at the top, change it to a 1. If you wish to set your cursor to the
	-- fifth one in your Mousecape list (counting from the top), set it to 5
	set cursorSelection to 1
	-- ***********************************************************************
	
	-- launch Mousecape at login
	delay 35
	tell application "Mousecape" to activate
	
	tell application "System Events"
		
		repeat (cursorSelection - 1) times
			delay 1
			-- key code 125 represents down arrow key
			key code 125
		end repeat
		
		delay 1
		-- key code 36 is the enter key, as command + enter sets the cape
		key code 36 using command down
		
	end tell
	
	-- Job done
	tell application "Mousecape" to quit
	
	return input
end run

```
And save the document as an `Application`.
Test it out by double clicking it! Bear in mind we wait 35 seconds before applying the cursor cape, as booting up can take a minute or two on different machines.

*If* (varies by Mac OS X version) Mac OS X/macOS nags you because of Assistive Access or an error message pops up with something along the lines of "Automator" and "XPC", follow on-screen instructions (if they appear, varies by Mac OS X version) or manually add the newly created app into your `System Preferences > Security & Privacy > Privacy > Accessibility` and, if available, `System Preferences > Security & Privacy > Privacy > Automation` lists. Then navigate to `/System/Library/CoreServices` and drag and drop `Automator Runner.app` and `System Events.app` into the(se) list(s) as well. This is needed as some Mac OS X/macOS configurations as of the last several few years tend to run into hiccups in some areas here - somewhat annoying if you don't know about it, so do it prophylactically.

Put the newly created .app into your login items in `System Preferences > Users & Groups > Login Items`.

You can comment out/remove the `"delay 1"` parts if your machine is quick enough.

Now it should work for everybody.

**Comment by NordJan** [comment]
@hipunk 👍 
Thanks, I followed your 'recipe', put everything in place, restarted, ran into an error message, fixed my own typo, restarted again and Mousecape is alive (after 35 secs). Cheers.
